# docker-compose -p sns-db-jpa up -d
version: "3.7"
services:
  sns-db-jpa:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sns-jpa
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=sns-svc
      - MYSQL_PASSWORD=sns-pass
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql-jpa:/var/lib/mysql